#!/bin/bash

echo "=== HƯỚNG DẪN ĐẨY DỰ ÁN LÊN GITHUB ==="
echo ""
echo "1. Tạo repository trên GitHub:"
echo "   - Truy cập https://github.com"
echo "   - Click 'New repository'"
echo "   - Đặt tên: tkw-website"
echo "   - Description: TKW Website - Dự án website công ty TKW"
echo "   - Chọn Public hoặc Private"
echo "   - KHÔNG check 'Add a README file'"
echo "   - Click 'Create repository'"
echo ""
echo "2. Sau khi tạo repository, copy URL của repository"
echo "   (Ví dụ: https://github.com/YOUR_USERNAME/tkw-website.git)"
echo ""
echo "3. Chạy lệnh sau (thay YOUR_USERNAME và REPOSITORY_NAME):"
echo "   git remote add origin https://github.com/YOUR_USERNAME/REPOSITORY_NAME.git"
echo ""
echo "4. Đẩy code lên GitHub:"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
echo "=== LỆNH MẪU ==="
echo "# Thay YOUR_USERNAME và REPOSITORY_NAME bằng thông tin thực tế"
echo "git remote add origin https://github.com/YOUR_USERNAME/REPOSITORY_NAME.git"
echo "git branch -M main"
echo "git push -u origin main"
echo ""
echo "Sau khi chạy xong, dự án sẽ được đẩy lên GitHub!" 